// Generates `permissions/autogenerated/commands/*.toml` and
// `permissions/schemas/schema.json` from the COMMANDS list below, following
// the Tauri v2 plugin-permissions build pattern. Don't hand-edit anything
// under `permissions/autogenerated/` — it's regenerated on every build.
//
// (c) Copyright 2026 Scott Morris
// SPDX-License-Identifier: Apache-2.0 OR MIT

const COMMANDS: &[&str] = &[
    "start",
    "stop",
    "set_speed",
    "set_mode",
    "add_critter",
    "rename_critter",
    "set_toggle",
    "set_theme",
    "set_frame",
    "get_snapshot",
    "load_snapshot",
];

fn main() {
    tauri_plugin::Builder::new(COMMANDS).build();
}
